name: Components Tests

on:
  pull_request:
    paths:
      - "packages/components/src/**/*.tsx"
      - "packages/components/src/**/*.snap"

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 16.x
        uses: actions/setup-node@v1
        with:
          node-version: 16.x
      - run: cd packages/components && yarn
      - run: cd packages/components && yarn test --spec --e2e
        env:
          CI: true
