name: End-to-End Tests

on:
  pull_request:
    branches:
      - main
      - next
      - fixes

jobs:
    e2e-playwright:
        runs-on: ubuntu-latest
        name: Playwright e2e tests
        strategy:
          matrix:
            browser: [chromium, firefox, webkit]
        steps:
            - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac # v4.0.0
              with:
                  show-progress: ${{ runner.debug == '1' && 'true' || 'false' }}

            - name: Yarn Install
              run: yarn

            - name: Plugin Build scripts
              run: |
                  yarn bootstrap
                  yarn release:build
                  yarn wp-scripts build
                  yarn composer:release
                  
            - name: Install WordPress and start the server
              run: |
                  yarn run wp-env start
                  yarn run wp-env run cli wp rewrite structure /%postname%/

            - name: Install Playwright dependencies
              run: npx playwright install ${{ matrix.browser }} --with-deps

            - name: Run the playwright tests
              run: yarn run test:e2e --browser ${{ matrix.browser }}

            - name: Stop the server
              run: yarn run wp-env stop
              if: always()
