name: Build Zip For QA

on:
  pull_request:
    types: [ labeled ]

jobs:
  build:
    if: ${{ github.event.label.name == 'qa ready' }}
    name: "Build Zip For QA"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - uses: ./.github/actions/build
        with:
          bootstrap: true
          package: true

      - name: Upload Zip
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: '@surecart/surecart.zip'
