name: Release

on:
  release:
    types: [published]

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          bootstrap: true
          package: true
          analytics_token: ${{ secrets.BSF_ANALYTICS_TOKEN }}

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: surecart
          BUILD_DIR: '@surecart/surecart'

      - name: Upload release asset
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: '@surecart/surecart.zip'
