name: Release

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      version:
        description: 'Version to use in commit message'
        required: false
        default: 'test'

jobs:
  release:
    name: "Release"
    runs-on: ubuntu-latest
    steps:
      - name: Install Subversion
        run: sudo apt-get update && sudo apt-get install -y subversion

      - uses: actions/checkout@v4

      - uses: ./.github/actions/build
        with:
          bootstrap: true
          package: true

      - name: WordPress Plugin Deploy
        uses: 10up/action-wordpress-plugin-deploy@stable
        env:
          SVN_PASSWORD: ${{ secrets.SVN_PASSWORD }}
          SVN_USERNAME: ${{ secrets.SVN_USERNAME }}
          SLUG: surecart
          BUILD_DIR: '@surecart/surecart'

      - name: Upload release asset
        uses: AButler/upload-release-assets@v2.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          files: '@surecart/surecart.zip'

      - name: Push to release repository
        id: push_directory
        uses: cpina/github-action-push-to-another-repository@main
        env:
          API_TOKEN_GITHUB: ${{ secrets.RELEASE_REPO_TOKEN }}
        with:
          source-directory: .
          destination-github-username: 'surecart'
          destination-repository-name: 'surecart-wp-plugin'
          user-email: support@surecart.com
          commit-message: Release version ${{ github.event.inputs.version || github.ref_name}}
          target-branch: main
